/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('planets').del()
  await knex('planets').insert([
    {
      id: 101,
      name: 'Sun',
      represent: 'The Sun represents your ego, identity, and role in life.',
      in_aries: '',
      in_taurus: '',
      in_gemini: '',
      in_cancer: '',
      in_leo: '',
      in_virgo: '',
      in_libra: '',
      in_scorpio: '',
      in_sagittarius: '',
      in_capricorn: '',
      in_aquarius: '',
      in_pisces: '',
    },
    {
      id: 102,
      name: 'Moon',
      represent: 'The Moon represents your emotions, moods, and feelings.',
      in_aries: '',
      in_taurus: '',
      in_gemini: '',
      in_cancer: '',
      in_leo: '',
      in_virgo: '',
      in_libra: '',
      in_scorpio: '',
      in_sagittarius: '',
      in_capricorn: '',
      in_aquarius: '',
      in_pisces: '',
    },
    {
      id: 103,
      name: 'Ascendant',
      represent:
        'The Ascendant represents your physical body and awakening consciousness.',
      in_aries: '',
      in_taurus: '',
      in_gemini: '',
      in_cancer: '',
      in_leo: '',
      in_virgo: '',
      in_libra: '',
      in_scorpio: '',
      in_sagittarius: '',
      in_capricorn: '',
      in_aquarius: '',
      in_pisces: '',
    },
    {
      id: 104,
      name: 'Mercury',
      represent:
        'Mercury represents how you communicate, talk, think, and process information.',
      in_aries: '',
      in_taurus: '',
      in_gemini: '',
      in_cancer: '',
      in_leo: '',
      in_virgo: '',
      in_libra: '',
      in_scorpio: '',
      in_sagittarius: '',
      in_capricorn: '',
      in_aquarius: '',
      in_pisces: '',
    },
    {
      id: 105,
      name: 'Venus',
      represent: 'Venus represents how and what you love.',
      in_aries: '',
      in_taurus: '',
      in_gemini: '',
      in_cancer: '',
      in_leo: '',
      in_virgo: '',
      in_libra: '',
      in_scorpio: '',
      in_sagittarius: '',
      in_capricorn: '',
      in_aquarius: '',
      in_pisces: '',
    },
    {
      id: 106,
      name: 'Mars',
      represent: 'Mars represents motivation, action, and sexuality.',
      in_aries: '',
      in_taurus: '',
      in_gemini: '',
      in_cancer: '',
      in_leo: '',
      in_virgo: '',
      in_libra: '',
      in_scorpio: '',
      in_sagittarius: '',
      in_capricorn: '',
      in_aquarius: '',
      in_pisces: '',
    },
    {
      id: 107,
      name: 'Jupiter',
      represent:
        'JUpiter represents growth, expansion, progress, and philosophy.',
      in_aries: '',
      in_taurus: '',
      in_gemini: '',
      in_cancer: '',
      in_leo: '',
      in_virgo: '',
      in_libra: '',
      in_scorpio: '',
      in_sagittarius: '',
      in_capricorn: '',
      in_aquarius: '',
      in_pisces: '',
    },
    {
      id: 108,
      name: 'Saturn',
      represent:
        'Saturn represents responsibility, restrictions, limits, boundaries, fears, and self-discipline.',
      in_aries: '',
      in_taurus: '',
      in_gemini: '',
      in_cancer: '',
      in_leo: '',
      in_virgo: '',
      in_libra: '',
      in_scorpio: '',
      in_sagittarius: '',
      in_capricorn: '',
      in_aquarius: '',
      in_pisces: '',
    },
    {
      id: 109,
      name: 'Uranus',
      represent:
        'Uranus represents innovation, progression, rebellion, and change.',
      in_aries: '',
      in_taurus: '',
      in_gemini: '',
      in_cancer: '',
      in_leo: '',
      in_virgo: '',
      in_libra: '',
      in_scorpio: '',
      in_sagittarius: '',
      in_capricorn: '',
      in_aquarius: '',
      in_pisces: '',
    },
    {
      id: 110,
      name: 'Neptune',
      represent: 'Neptune represents dreams, imagination, and the unconscious.',
      in_aries: '',
      in_taurus: '',
      in_gemini: '',
      in_cancer: '',
      in_leo: '',
      in_virgo: '',
      in_libra: '',
      in_scorpio: '',
      in_sagittarius: '',
      in_capricorn: '',
      in_aquarius: '',
      in_pisces: '',
    },
    {
      id: 111,
      name: 'Pluto',
      represent:
        'Pluto represents power, intensity, obsession, control, and transformation.',
      in_aries: '',
      in_taurus: '',
      in_gemini: '',
      in_cancer: '',
      in_leo: '',
      in_virgo: '',
      in_libra: '',
      in_scorpio: '',
      in_sagittarius: '',
      in_capricorn: '',
      in_aquarius: '',
      in_pisces: '',
    },
  ])
}
